title: <p align="center"> Idhaya R </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/idhaya-r/">LinkedIn</a> |
  <a href="https://github.com/idhaya-r">GitHub</a>
  
  <br>   In search of wisdom.  <br>
  </p>



theme: jekyll-theme-minimal
